create table elections (
    id bigint generated by default as identity primary key,
    sg_id varchar(20) not null,
    sg_typecode varchar(10) not null,
    name varchar(100) not null,
    votedate date,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_elections_code unique (sg_id, sg_typecode)
);

create table candidates (
    id bigint generated by default as identity primary key,
    election_id bigint not null references elections(id) on delete cascade,
    external_id varchar(40) not null,
    name varchar(100) not null,
    party_name varchar(100),
    sd_name varchar(100),
    sgg_name varchar(100),
    wiw_name varchar(100),
    status varchar(50),
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_candidates_external unique (election_id, external_id)
);

create table pledges (
    id bigint generated by default as identity primary key,
    candidate_id bigint not null references candidates(id) on delete cascade,
    external_order integer not null,
    category varchar(100),
    title varchar(500) not null,
    raw_content text not null,
    summary text,
    summary_status varchar(30) not null default 'PENDING',
    summary_model varchar(100),
    summary_generated_at timestamp,
    source_hash varchar(128),
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_pledges_candidate_order unique (candidate_id, external_order)
);

create index idx_candidates_election_id on candidates(election_id);
create index idx_pledges_candidate_id on pledges(candidate_id);
create index idx_pledges_summary_status on pledges(summary_status);

